apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - console-link.yaml
  - milvus-configs.yaml
  - milvus-pvc.yaml
  - milvus-dep.yaml
  - milvus-svc.yaml
  - milvus-rt.yaml
